package org.pikvm.webrtc;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.reflect.TypeToken;
import okhttp3.MediaType;
import okhttp3.RequestBody;
import okhttp3.Response;
import org.pikvm.exception.PiKvmNetworkException;
import org.pikvm.exception.PiKvmStreamException;
import org.pikvm.http.PiKvmHttpClient;
import org.pikvm.websocket.PiKvmWebSocketClient;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Consumer;
import java.util.logging.Logger;

/**
 * Handles the WebRTC signaling exchange with a PiKVM device.
 *
 * <p>PiKVM exposes a REST-based signaling endpoint at
 * {@code /api/streamer/webrtc}.  This class implements the offer/answer
 * handshake and listens for trickle ICE candidates that PiKVM delivers over
 * the WebSocket connection.</p>
 *
 * <h3>Negotiation flow</h3>
 * <ol>
 *   <li>Caller creates an SDP offer using a WebRTC peer-connection library.</li>
 *   <li>{@link #negotiate} POSTs the offer and returns the SDP answer.</li>
 *   <li>Caller sets the answer as the remote description.</li>
 *   <li>{@link #startIceCandidateListener} begins monitoring the WebSocket for
 *       ICE candidates sent by the PiKVM device.</li>
 * </ol>
 *
 * <h3>PiKVM API</h3>
 * <pre>
 * POST /api/streamer/webrtc
 * Content-Type: application/json
 * {"sdp": "&lt;offer&gt;", "video": true, "audio": true}
 *
 * 200 OK
 * {"ok": true, "result": {"sdp": "&lt;answer&gt;"}}
 *
 * GET /api/streamer/webrtc
 * {"ok": true, "result": {"ice_servers": ["stun:…"]}}
 * </pre>
 *
 * <p>ICE candidates arrive via WebSocket as:
 * <pre>
 * {"event_type": "streamer_webrtc",
 *  "event": {"ice_candidate": {"candidate": "…", "sdpMid": "0", "sdpMLineIndex": 0}}}
 * </pre></p>
 */
public class WebRtcSignalingClient {

    private static final Logger    LOGGER     = Logger.getLogger(WebRtcSignalingClient.class.getName());
    private static final String    WEBRTC_PATH = "/api/streamer/webrtc";
    private static final MediaType JSON_MT     = MediaType.parse("application/json; charset=utf-8");
    private static final Gson      GSON        = new Gson();

    private final PiKvmHttpClient      httpClient;
    private volatile PiKvmWebSocketClient wsClient;

    private final AtomicBoolean  listening = new AtomicBoolean(false);
    private volatile ExecutorService listenerExecutor;

    /**
     * Constructs a signaling client.
     *
     * @param httpClient authenticated HTTP client
     * @param wsClient   WebSocket client used to receive ICE candidates
     *                   (may be {@code null}; set later via {@link #setWsClient})
     */
    public WebRtcSignalingClient(PiKvmHttpClient httpClient, PiKvmWebSocketClient wsClient) {
        this.httpClient = httpClient;
        this.wsClient   = wsClient;
    }

    // ── SDP negotiation ───────────────────────────────────────────────────

    /**
     * Exchanges an SDP offer with PiKVM and returns the SDP answer.
     *
     * <p>POSTs {@code {"sdp": sdpOffer, "video": video, "audio": audio}} to
     * {@code /api/streamer/webrtc} and parses the JSON answer.</p>
     *
     * @param sdpOffer SDP offer string generated by the WebRTC peer connection
     * @param video    {@code true} to request video from PiKVM
     * @param audio    {@code true} to request audio from PiKVM
     * @return the SDP answer from PiKVM
     * @throws PiKvmStreamException  if the server rejects the offer or returns an empty answer
     * @throws PiKvmNetworkException if the HTTP request fails
     */
    @SuppressWarnings("unchecked")
    public WebRtcSessionDescription negotiate(String sdpOffer, boolean video, boolean audio) {
        JsonObject body = new JsonObject();
        body.addProperty("sdp",   sdpOffer);
        body.addProperty("video", video);
        body.addProperty("audio", audio);

        try (Response resp = httpClient.post(WEBRTC_PATH, null,
                RequestBody.create(GSON.toJson(body), JSON_MT))) {

            if (resp.body() == null) {
                throw new PiKvmStreamException("WebRTC negotiation returned empty body (HTTP " + resp.code() + ")");
            }
            String bodyStr = resp.body().string();
            LOGGER.fine("WebRTC negotiate response: " + bodyStr);

            if (!resp.isSuccessful()) {
                throw new PiKvmStreamException("WebRTC negotiation failed: HTTP " + resp.code()
                        + " – " + bodyStr);
            }

            Map<String, Object> root = GSON.fromJson(bodyStr,
                    new TypeToken<Map<String, Object>>() {}.getType());

            if (!Boolean.TRUE.equals(root.get("ok"))) {
                throw new PiKvmStreamException("PiKVM rejected WebRTC offer: " + bodyStr);
            }

            Map<String, Object> result = (Map<String, Object>) root.get("result");
            if (result == null) {
                throw new PiKvmStreamException("Missing 'result' in WebRTC negotiate response");
            }
            String sdpAnswer = (String) result.get("sdp");
            if (sdpAnswer == null || sdpAnswer.isEmpty()) {
                throw new PiKvmStreamException("Empty SDP answer received from PiKVM");
            }
            LOGGER.info("WebRTC SDP negotiation successful");
            return new WebRtcSessionDescription("answer", sdpAnswer);

        } catch (IOException e) {
            throw new PiKvmNetworkException("WebRTC negotiate HTTP error", e);
        }
    }

    // ── ICE server discovery ──────────────────────────────────────────────

    /**
     * Returns the ICE server list published by PiKVM.
     *
     * <p>GETs {@code /api/streamer/webrtc} and extracts the
     * {@code result.ice_servers} array.  Falls back to Google's public STUN
     * server if the endpoint is unavailable or returns no servers.</p>
     *
     * @return list of STUN/TURN URL strings
     */
    @SuppressWarnings("unchecked")
    public List<String> getIceServers() {
        try (Response resp = httpClient.get(WEBRTC_PATH)) {
            if (resp.isSuccessful() && resp.body() != null) {
                Map<String, Object> root = GSON.fromJson(resp.body().string(),
                        new TypeToken<Map<String, Object>>() {}.getType());
                Object resultObj = root.get("result");
                if (resultObj instanceof Map) {
                    Object iceObj = ((Map<String, Object>) resultObj).get("ice_servers");
                    if (iceObj instanceof List) {
                        List<String> servers = new ArrayList<>();
                        for (Object s : (List<?>) iceObj) {
                            if (s instanceof String) servers.add((String) s);
                        }
                        if (!servers.isEmpty()) {
                            LOGGER.fine("ICE servers from PiKVM: " + servers);
                            return servers;
                        }
                    }
                }
            }
        } catch (IOException | ClassCastException e) {
            LOGGER.warning("Could not fetch ICE servers from PiKVM: " + e.getMessage());
        }
        LOGGER.fine("Using default STUN server");
        return defaultIceServers();
    }

    // ── ICE candidate listener ────────────────────────────────────────────

    /**
     * Starts a background thread that forwards ICE candidates sent by PiKVM
     * over the WebSocket to the given {@code callback}.
     *
     * <p>PiKVM sends ICE candidates as:
     * <pre>{"event_type": "streamer_webrtc",
     *  "event": {"ice_candidate": {…}}}</pre></p>
     *
     * <p>Call {@link #stopIceCandidateListener()} to terminate the thread.</p>
     *
     * @param callback invoked on the listener thread for each candidate
     */
    public void startIceCandidateListener(Consumer<WebRtcIceCandidate> callback) {
        if (!listening.compareAndSet(false, true)) {
            LOGGER.fine("ICE candidate listener already running");
            return;
        }
        listenerExecutor = Executors.newSingleThreadExecutor(r -> {
            Thread t = new Thread(r, "pikvm-webrtc-ice-listener");
            t.setDaemon(true);
            return t;
        });
        listenerExecutor.submit(() -> {
            LOGGER.fine("WebRTC ICE candidate listener started");
            while (listening.get() && !Thread.currentThread().isInterrupted()) {
                try {
                    PiKvmWebSocketClient ws = wsClient;
                    if (ws == null) {
                        Thread.sleep(100);
                        continue;
                    }
                    Map<String, Object> msg = ws.getJsonMessage();
                    WebRtcIceCandidate candidate = parseIceCandidate(msg);
                    if (candidate != null) {
                        LOGGER.fine("Received ICE candidate from PiKVM: " + candidate);
                        callback.accept(candidate);
                    }
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                } catch (Exception e) {
                    LOGGER.fine("ICE listener error: " + e.getMessage());
                }
            }
            LOGGER.fine("WebRTC ICE candidate listener stopped");
        });
    }

    /**
     * Stops the background ICE candidate listener thread.
     */
    public void stopIceCandidateListener() {
        listening.set(false);
        ExecutorService exec = listenerExecutor;
        if (exec != null) {
            exec.shutdownNow();
            listenerExecutor = null;
        }
    }

    // ── Accessors ─────────────────────────────────────────────────────────

    /** Replaces the WebSocket client used for ICE candidate events. */
    public void setWsClient(PiKvmWebSocketClient wsClient) {
        this.wsClient = wsClient;
    }

    public PiKvmWebSocketClient getWsClient() { return wsClient; }

    // ── Internal helpers ──────────────────────────────────────────────────

    @SuppressWarnings("unchecked")
    private static WebRtcIceCandidate parseIceCandidate(Map<String, Object> msg) {
        if (msg == null) return null;
        if (!"streamer_webrtc".equals(msg.get("event_type"))) return null;
        try {
            Map<String, Object> event = (Map<String, Object>) msg.get("event");
            if (event == null) return null;
            Map<String, Object> ice = (Map<String, Object>) event.get("ice_candidate");
            if (ice == null) return null;

            String candidate = (String) ice.get("candidate");
            String sdpMid    = (String) ice.get("sdpMid");
            int sdpMLineIdx  = ice.get("sdpMLineIndex") instanceof Number
                    ? ((Number) ice.get("sdpMLineIndex")).intValue() : 0;

            if (candidate == null || candidate.isEmpty()) return null;
            return new WebRtcIceCandidate(candidate, sdpMid != null ? sdpMid : "0", sdpMLineIdx);
        } catch (ClassCastException e) {
            return null;
        }
    }

    private static List<String> defaultIceServers() {
        List<String> servers = new ArrayList<>();
        servers.add("stun:stun.l.google.com:19302");
        return servers;
    }
}
