package org.pikvm.webrtc;

/**
 * Represents a WebRTC Session Description Protocol (SDP) message.
 *
 * <p>Used in the offer/answer exchange during WebRTC negotiation with PiKVM.
 * The {@code type} is either {@code "offer"} (generated by the client) or
 * {@code "answer"} (received from the PiKVM device).</p>
 */
public final class WebRtcSessionDescription {

    private final String type;
    private final String sdp;

    /**
     * Creates a new SDP description.
     *
     * @param type one of {@code "offer"} or {@code "answer"}
     * @param sdp  the SDP body string
     */
    public WebRtcSessionDescription(String type, String sdp) {
        this.type = type;
        this.sdp  = sdp;
    }

    /** Returns {@code "offer"} or {@code "answer"}. */
    public String getType() { return type; }

    /** Returns the raw SDP text. */
    public String getSdp()  { return sdp; }

    @Override
    public String toString() {
        return "WebRtcSessionDescription{type='" + type + "', sdpLength=" + (sdp == null ? 0 : sdp.length()) + "}";
    }
}
