plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm' version '1.9.22'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    api project(':pikvm-core')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.22"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
}
